# Site settings
title: Data Visualization
tagline: Exploratory Data Analysis and Visualization

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
email: myemail@me.com
description: > # this means to ignore newlines until "baseurl:"
  This is cool
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
