# Site settings
title: Roberto's Data Visualization
tagline: Exploratory Data Analysis and Visualization

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
email: roberto@me.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bertomartin.github.io" # the base hostname & protocol for your site
twitter_username: bertobully
github_username:  bertomartin

# Build settings
markdown: kramdown
